### ISSUE TITLE
await for StartVideoStreaming waits endlessly

### ISSUE THREAD

**Issue by OlJohnny** [emiliodallatorre/flutter_rtmp_broadcaster#15]
when using the code from the example,

<code>await cameraController!.startVideoStreaming(url);</code>

it just awaits endlessly and no actual video gets streamed.

if anybody has any ideas of what to try out, or some stuff to check for errors, please let me know.

**Comment by OlJohnny** [comment]
As far as I can tell, the corresponding <code>startVideoStreaming</code> method inside <code>android/src/main/kotlin/com/app/rtmp_publisher</code> doesnt get called.

**Comment by emiliodallatorre** [comment]
Hi @OlJohnny,
does this issue persist with latest plugin version?
Can you please provide a logcat?

**Comment by luo3house** [comment]
Met the same problem, it causes when you await `initialize()` and then quickly go on with `startVideoStreaming` while the surface of camera preview is NOT ready yet.

Here's a tiny commit for this fix, no any code changes needed. Have fun if it could help you. Or I would pull request if the project is maintaining.
https://github.com/luo3house/flutter_rtmp_broadcaster/commit/479f6ebe9557eb0f379620e2823deaaad2276817

```yaml
rtmp_broadcaster:
    git:
      url: https://github.com/luo3house/flutter_rtmp_broadcaster.git
      ref: 479f6ebe9557eb0f379620e2823deaaad2276817
```
